dist: xenial
language: python
python: 3.7

install:
  - python -m pip install -r requirements_travis_ci.txt

script:
  - python -m pytest --cov=huntsville_havoc tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
